/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utama;

import LaporanPenjualan.LaporanKategori;
import LaporanPenjualan.LaporanLaba;
import LaporanPenjualan.LaporanOmset;
import Master_Data.dataBarang1;
import Master_Data.dataPelanggan;
import Master_Data.dataSuplier;
import Master_Data.dataUser;
import Pembelian.Pembelian;
import Penjualan.Penjualan;
import com.util.FormUtil;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import org.mindrot.BCrypt;


/**
 *
 * @author LENOVO
 */
public class Main extends javax.swing.JFrame {

    Connection conn= (Connection)koneksi.configDB();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setExtendedState(Main.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextFieldnmUser = new javax.swing.JTextField();
        jPasswordFieldpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonlogin = new javax.swing.JButton();
        jDesktopPane_main = new javax.swing.JDesktopPane() {
            private Image image;
            {
                try {
                    image = ImageIO.read(new URL("https://res.cloudinary.com/smegamart-softdev/image/upload/v1663380859/layer%20utama/tampak-depan_rqgrhb.jpg"));
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuMasterData = new javax.swing.JMenu();
        jMenuItemDataBarang = new javax.swing.JMenuItem();
        jMenuItemPelanggan = new javax.swing.JMenuItem();
        jMenuItemSupplier = new javax.swing.JMenuItem();
        jMenuItemUser = new javax.swing.JMenuItem();
        jMenuPenjualan = new javax.swing.JMenu();
        jMenuItemPenjualan = new javax.swing.JMenuItem();
        jMenuLaporanPenjualan = new javax.swing.JMenu();
        jMenuItemLapOmset = new javax.swing.JMenuItem();
        jMenuItemLapLaba = new javax.swing.JMenuItem();
        jMenuItemLapPenjualanKategori = new javax.swing.JMenuItem();
        jMenuItemLaporanPenjualanKasir = new javax.swing.JMenuItem();
        jMenuPembelian = new javax.swing.JMenu();
        jMenuItemPembelian = new javax.swing.JMenuItem();
        jMenuItemLaporanPembelian = new javax.swing.JMenuItem();

        jDialog1.setTitle("LOGIN");
        jDialog1.setSize(new java.awt.Dimension(400, 235));

        jTextFieldnmUser.setText("Admin");

        jPasswordFieldpassword.setText("SMart@2022");

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        jButtonlogin.setText("LOGIN");
        jButtonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldnmUser, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldnmUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonlogin)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMEGA MART");

        javax.swing.GroupLayout jDesktopPane_mainLayout = new javax.swing.GroupLayout(jDesktopPane_main);
        jDesktopPane_main.setLayout(jDesktopPane_mainLayout);
        jDesktopPane_mainLayout.setHorizontalGroup(
            jDesktopPane_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        jDesktopPane_mainLayout.setVerticalGroup(
            jDesktopPane_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(187, 23, 36));
        jMenuBar1.setEnabled(false);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(266, 30));
        jMenuBar1.setBackground(new Color(187, 23, 36));
        jMenuBar1.setOpaque(true);

        jMenuHome.setForeground(java.awt.Color.white);
        jMenuHome.setText("Home");
        jMenuHome.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jMenuItemLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuHome.add(jMenuItemLogin);

        jMenuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.setEnabled(false);
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuHome.add(jMenuItemLogout);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuHome.add(jMenuItemExit);

        jMenuBar1.add(jMenuHome);

        jMenuMasterData.setForeground(java.awt.Color.white);
        jMenuMasterData.setText("Master Data");
        jMenuMasterData.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jMenuItemDataBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemDataBarang.setText("Data Barang");
        jMenuItemDataBarang.setEnabled(false);
        jMenuItemDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDataBarangActionPerformed(evt);
            }
        });
        jMenuMasterData.add(jMenuItemDataBarang);

        jMenuItemPelanggan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemPelanggan.setText("Pelanggan");
        jMenuItemPelanggan.setEnabled(false);
        jMenuItemPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPelangganActionPerformed(evt);
            }
        });
        jMenuMasterData.add(jMenuItemPelanggan);

        jMenuItemSupplier.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSupplier.setText("Supplier");
        jMenuItemSupplier.setEnabled(false);
        jMenuItemSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSupplierActionPerformed(evt);
            }
        });
        jMenuMasterData.add(jMenuItemSupplier);

        jMenuItemUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemUser.setText("User");
        jMenuItemUser.setEnabled(false);
        jMenuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUserActionPerformed(evt);
            }
        });
        jMenuMasterData.add(jMenuItemUser);

        jMenuBar1.add(jMenuMasterData);

        jMenuPenjualan.setForeground(java.awt.Color.white);
        jMenuPenjualan.setText("Penjualan");
        jMenuPenjualan.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jMenuItemPenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemPenjualan.setText("Penjualan");
        jMenuItemPenjualan.setEnabled(false);
        jMenuItemPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPenjualanActionPerformed(evt);
            }
        });
        jMenuPenjualan.add(jMenuItemPenjualan);

        jMenuLaporanPenjualan.setText("Laporan Penjualan");
        jMenuLaporanPenjualan.setEnabled(false);

        jMenuItemLapOmset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemLapOmset.setText("Laporan Omset");
        jMenuItemLapOmset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLapOmsetActionPerformed(evt);
            }
        });
        jMenuLaporanPenjualan.add(jMenuItemLapOmset);

        jMenuItemLapLaba.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemLapLaba.setText("Laporan Laba");
        jMenuItemLapLaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLapLabaActionPerformed(evt);
            }
        });
        jMenuLaporanPenjualan.add(jMenuItemLapLaba);

        jMenuItemLapPenjualanKategori.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLapPenjualanKategori.setText("Laporan Penjualan Kategori");
        jMenuItemLapPenjualanKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLapPenjualanKategoriActionPerformed(evt);
            }
        });
        jMenuLaporanPenjualan.add(jMenuItemLapPenjualanKategori);

        jMenuItemLaporanPenjualanKasir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLaporanPenjualanKasir.setText("Laporan Penjualan Kasir");
        jMenuLaporanPenjualan.add(jMenuItemLaporanPenjualanKasir);

        jMenuPenjualan.add(jMenuLaporanPenjualan);

        jMenuBar1.add(jMenuPenjualan);

        jMenuPembelian.setForeground(java.awt.Color.white);
        jMenuPembelian.setText("Pembelian");
        jMenuPembelian.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jMenuItemPembelian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemPembelian.setText("Pembelian");
        jMenuItemPembelian.setEnabled(false);
        jMenuItemPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPembelianActionPerformed(evt);
            }
        });
        jMenuPembelian.add(jMenuItemPembelian);

        jMenuItemLaporanPembelian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemLaporanPembelian.setText("Laporan Pembelian");
        jMenuItemLaporanPembelian.setEnabled(false);
        jMenuPembelian.add(jMenuItemLaporanPembelian);

        jMenuBar1.add(jMenuPembelian);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane_main)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane_main)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        FormUtil.centerWindow(jDialog1);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDataBarangActionPerformed
        dataBarang1 db = new dataBarang1();
        jDesktopPane_main.add(db);
        try {
            db.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        db.setVisible(true);
    }//GEN-LAST:event_jMenuItemDataBarangActionPerformed

    private void jMenuItemPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPenjualanActionPerformed
        Penjualan pj = new Penjualan();
        jDesktopPane_main.add(pj);
        try {
            pj.setMaximum(true);
        } catch (Exception e) {
        }
        pj.setVisible(true);
        pj.txtBarcode.requestFocus();
    }//GEN-LAST:event_jMenuItemPenjualanActionPerformed

    private void jButtonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloginActionPerformed
        // TODO add your handling code here:
         if (jTextFieldnmUser.getText().length()==0) {
                jTextFieldnmUser.requestFocus();
            } else if(jPasswordFieldpassword.getText().length()==0) {
                jPasswordFieldpassword.requestFocus();
            } else {
                String nmUser = jTextFieldnmUser.getText();
                String pwd = jPasswordFieldpassword.getText();

                String query = "select kdUser,password,level from datauser where namaUser= '"+nmUser+"'";
                try {
                    Statement stm=conn.createStatement();
                    ResultSet rs=stm.executeQuery(query);
                    
                    if (rs.next()) {
                        String kdUser =rs.getString("kdUser");
                        String pwd1 = rs.getString("password").replaceFirst("2y", "2a");
                        String level = rs.getString("level");
                        
                        if (BCrypt.checkpw(pwd, pwd1)) {
                            Variabel.setkodeUser(kdUser);
                            Variabel.setUserLogin(nmUser);
                            JOptionPane.showMessageDialog(null, "Berhasil Login");
                            jDialog1.setVisible(false);
                            jDialog1.dispose();
                            
                            if (level.equals("Admin")) {
                                tampil_admin();
                            } else if(level.equals("Kasir")) {
                                tampil_kasir();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "password salah");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "username salah");
                    }
                } catch (Exception e) {
                }
            }
    }//GEN-LAST:event_jButtonloginActionPerformed

    private void jMenuItemPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPelangganActionPerformed
        // TODO add your handling code here:
        dataPelanggan dp = new dataPelanggan();
        jDesktopPane_main.add(dp);
        
        try {
            dp.setMaximum(true);
        } catch (Exception e) {
            
        }
        dp.setVisible(true);
    }//GEN-LAST:event_jMenuItemPelangganActionPerformed

    private void jMenuItemSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSupplierActionPerformed
        // TODO add your handling code here:
        dataSuplier ds = new dataSuplier();
        jDesktopPane_main.add(ds);
        
        try {
            ds.setMaximum(true);
        } catch (Exception e) {
            
        }
        ds.setVisible(true);
    }//GEN-LAST:event_jMenuItemSupplierActionPerformed

    private void jMenuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserActionPerformed
        // TODO add your handling code here:
        dataUser du = new dataUser();
        jDesktopPane_main.add(du);
        
        try {
            du.setMaximum(true);
        } catch (Exception e) {
            
        }
        du.setVisible(true);
    }//GEN-LAST:event_jMenuItemUserActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
       jMenuItemLogin.setEnabled(true);
       jMenuItemLogout.setEnabled(false);
       jMenuItemDataBarang.setEnabled(false);
       jMenuItemPelanggan.setEnabled(false);
       jMenuItemSupplier.setEnabled(false);
       jMenuItemUser.setEnabled(false);
       jMenuItemPenjualan.setEnabled(false);
       jMenuLaporanPenjualan.setEnabled(false);
       jMenuItemPembelian.setEnabled(false);
       jMenuItemLaporanPembelian.setEnabled(false);
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemLapOmsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLapOmsetActionPerformed
        // TODO add your handling code here:
        LaporanOmset lo = new LaporanOmset();
        jDesktopPane_main.add(lo);
        
        try {
            lo.setMaximum(true);
        } catch (Exception e) {
            
        }
        lo.setVisible(true);
    }//GEN-LAST:event_jMenuItemLapOmsetActionPerformed

    private void jMenuItemPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPembelianActionPerformed
        // TODO add your handling code here:
        Pembelian pb = new Pembelian();
        jDesktopPane_main.add(pb);
        
        try {
            pb.setMaximum(true);
        } catch (Exception e) {
            
        }
        pb.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemPembelianActionPerformed

    private void jMenuItemLapLabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLapLabaActionPerformed
        // TODO add your handling code here:
        LaporanLaba lb = new LaporanLaba();
        jDesktopPane_main.add(lb);
        
        try {
            lb.setMaximum(true);
        } catch (Exception e) {
            
        }
        lb.setVisible(true);
    }//GEN-LAST:event_jMenuItemLapLabaActionPerformed

    private void jMenuItemLapPenjualanKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLapPenjualanKategoriActionPerformed
        // TODO add your handling code here:
        LaporanKategori lb = new LaporanKategori();
        jDesktopPane_main.add(lb);
        
        try {
            lb.setMaximum(true);
        } catch (Exception e) {
            
        }
        lb.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemLapPenjualanKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonlogin;
    private javax.swing.JDesktopPane jDesktopPane_main;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenuItem jMenuItemDataBarang;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLapLaba;
    private javax.swing.JMenuItem jMenuItemLapOmset;
    private javax.swing.JMenuItem jMenuItemLapPenjualanKategori;
    private javax.swing.JMenuItem jMenuItemLaporanPembelian;
    private javax.swing.JMenuItem jMenuItemLaporanPenjualanKasir;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPelanggan;
    private javax.swing.JMenuItem jMenuItemPembelian;
    private javax.swing.JMenuItem jMenuItemPenjualan;
    private javax.swing.JMenuItem jMenuItemSupplier;
    private javax.swing.JMenuItem jMenuItemUser;
    private javax.swing.JMenu jMenuLaporanPenjualan;
    private javax.swing.JMenu jMenuMasterData;
    private javax.swing.JMenu jMenuPembelian;
    private javax.swing.JMenu jMenuPenjualan;
    private javax.swing.JPasswordField jPasswordFieldpassword;
    private javax.swing.JTextField jTextFieldnmUser;
    // End of variables declaration//GEN-END:variables

    private void tampil_admin() {
       jMenuItemLogin.setEnabled(false);
       jMenuItemLogout.setEnabled(true);
       jMenuItemDataBarang.setEnabled(true);
       jMenuItemPelanggan.setEnabled(true);
       jMenuItemSupplier.setEnabled(true);
       jMenuItemUser.setEnabled(true);
       jMenuItemPenjualan.setEnabled(true);
       jMenuLaporanPenjualan.setEnabled(true);
       jMenuItemPembelian.setEnabled(true);
       jMenuItemLaporanPembelian.setEnabled(true);
       
    }

    private void tampil_kasir() {
        jMenuItemLogin.setEnabled(false);
       jMenuItemLogout.setEnabled(true);
       jMenuItemDataBarang.setEnabled(false);
       jMenuItemPelanggan.setEnabled(false);
       jMenuItemSupplier.setEnabled(false);
       jMenuItemUser.setEnabled(false);
       jMenuItemPenjualan.setEnabled(true);
       jMenuLaporanPenjualan.setEnabled(false);
       jMenuItemPembelian.setEnabled(false);
       jMenuItemLaporanPembelian.setEnabled(false);
    }
    
   
}
