/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master_Data;

import com.util.FormUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author LENOVO
 */
public class dataSuplier extends javax.swing.JInternalFrame {

    Connection conn= (Connection)koneksi.configDB();
    /**
     * Creates new form dataBarang1
     */
    public dataSuplier() {
        initComponents();
        load_table();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogSupplier = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNamaSuplierOk = new javax.swing.JTextField();
        jTextFieldKdSupplierOK = new javax.swing.JTextField();
        jButtonSimpanSupplier = new javax.swing.JButton();
        jPopupMenuSupplier = new javax.swing.JPopupMenu();
        jMenuItemEdit = new javax.swing.JMenuItem();
        jMenuItemHapus = new javax.swing.JMenuItem();
        jDialogEditSupplier = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNamaSupplierEdit = new javax.swing.JTextField();
        jTextFieldKodeSupplierEdit = new javax.swing.JTextField();
        jButtonSupplierEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSupplier = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtontmbhSupplier = new javax.swing.JButton();

        jDialogSupplier.setTitle("Tambah Supplier");
        jDialogSupplier.setSize(new java.awt.Dimension(400, 350));

        jLabel1.setText("Kode Supplier");

        jLabel2.setText("Nama Supplier");

        jButtonSimpanSupplier.setText("Simpan");
        jButtonSimpanSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogSupplierLayout = new javax.swing.GroupLayout(jDialogSupplier.getContentPane());
        jDialogSupplier.getContentPane().setLayout(jDialogSupplierLayout);
        jDialogSupplierLayout.setHorizontalGroup(
            jDialogSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSupplierLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jDialogSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSupplierLayout.createSequentialGroup()
                        .addGroup(jDialogSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(jDialogSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldKdSupplierOK, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaSuplierOk, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonSimpanSupplier))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jDialogSupplierLayout.setVerticalGroup(
            jDialogSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldKdSupplierOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDialogSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNamaSuplierOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButtonSimpanSupplier)
                .addContainerGap())
        );

        jMenuItemEdit.setText("Edit");
        jMenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditActionPerformed(evt);
            }
        });
        jPopupMenuSupplier.add(jMenuItemEdit);

        jMenuItemHapus.setText("Hapus");
        jMenuItemHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHapusActionPerformed(evt);
            }
        });
        jPopupMenuSupplier.add(jMenuItemHapus);

        jDialogEditSupplier.setTitle("Edit Barang");
        jDialogEditSupplier.setSize(new java.awt.Dimension(400, 300));

        jLabel8.setText("Kode Supplier");

        jLabel9.setText("Nama Supplier");

        jButtonSupplierEdit.setText("Edit");
        jButtonSupplierEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupplierEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogEditSupplierLayout = new javax.swing.GroupLayout(jDialogEditSupplier.getContentPane());
        jDialogEditSupplier.getContentPane().setLayout(jDialogEditSupplierLayout);
        jDialogEditSupplierLayout.setHorizontalGroup(
            jDialogEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditSupplierLayout.createSequentialGroup()
                        .addGroup(jDialogEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37)
                        .addGroup(jDialogEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldKodeSupplierEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaSupplierEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonSupplierEdit))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jDialogEditSupplierLayout.setVerticalGroup(
            jDialogEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldKodeSupplierEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDialogEditSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNamaSupplierEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButtonSupplierEdit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setTitle("Data Supplier");

        jTableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSupplier.setComponentPopupMenu(jPopupMenuSupplier);
        jTableSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSupplier);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtontmbhSupplier.setText("Tambah Supplier");
        jButtontmbhSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontmbhSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtontmbhSupplier)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtontmbhSupplier)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtontmbhSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontmbhSupplierActionPerformed
//        FormUtil.centerWindow(jDialogSuplier);
        FormUtil.centerWindow(jDialogSupplier);
        jDialogSupplier.setVisible(true);
    }//GEN-LAST:event_jButtontmbhSupplierActionPerformed

    private void jButtonSimpanSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanSupplierActionPerformed
        if(jTextFieldKdSupplierOK.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Kode Supplier");
        }else if(jTextFieldNamaSuplierOk.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Nama Supplier");
        }else{
            String kdsupplier = jTextFieldKdSupplierOK.getText();
            String namasupplier = jTextFieldNamaSuplierOk.getText();
           
            
            String query ="INSERT INTO `datasupplier` (`kdSupplier`, `namasupplier`) VALUES ('"+kdsupplier+"', '"+namasupplier+"')";
            try {
                int pilihan = JOptionPane.showConfirmDialog(null, "Simpan data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    clear();
                    load_table();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }

    private void load_table1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
    }//GEN-LAST:event_jButtonSimpanSupplierActionPerformed

    private void jButtonSupplierEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupplierEditActionPerformed
        // TODO add your handling code here:
        if(jTextFieldKodeSupplierEdit.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Kode Supplier");
        }else if(jTextFieldNamaSupplierEdit.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Nama Supplier");
        }else{
            String kdSupplier = jTextFieldKodeSupplierEdit.getText();
            String namaSupplier = jTextFieldNamaSupplierEdit.getText();
            
            String query ="update `datasupplier` set `kdSupplier`= '"+kdSupplier+"', `namaSupplier`='"+namaSupplier+"' where kdSupplier = '"+kdSupplier+"'";
            try {
                int pilihan = JOptionPane.showConfirmDialog(null, "Simpan data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    jDialogEditSupplier.setVisible(false);
                    jDialogEditSupplier.dispose();
                    clear();
                    load_table();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
        }
    }//GEN-LAST:event_jButtonSupplierEditActionPerformed

    private void jTableSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSupplierMouseClicked
        // TODO add your handling code here:
        // menampilkan data kedalam form pengisian:
        
        int baris = jTableSupplier.rowAtPoint(evt.getPoint());
        String kdSpplier =jTableSupplier.getValueAt(baris, 0).toString();
        jTextFieldKodeSupplierEdit.setText(kdSpplier);
//        String nmSpplier =jTableSupplier.getValueAt(baris, 1).toString();
//        jTextFieldNamaSupplierEdit.setText(nmSpplier);
        
        String query = "SELECT kdSupplier, namaSupplier from datasupplier where kdSupplier = '"+kdSpplier+"'";
        try {
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            
            if(res.next()){
                jTextFieldKodeSupplierEdit.setText(res.getString("kdSupplier"));
                jTextFieldNamaSupplierEdit.setText(res.getString("namaSupplier"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTableSupplierMouseClicked

    private void jMenuItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditActionPerformed
        FormUtil.centerWindow(jDialogEditSupplier);
        jDialogEditSupplier.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditActionPerformed

    private void jMenuItemHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHapusActionPerformed
            
        String kdSupplier = jTextFieldKodeSupplierEdit.getText();
        String query_hapus = "delete from datasupplier where kdSupplier = '"+kdSupplier+"'";
        try {
            int pilihan = JOptionPane.showConfirmDialog(null, "Hapus data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query_hapus);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    
                    clear();
                    load_table();
                }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jMenuItemHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSimpanSupplier;
    private javax.swing.JButton jButtonSupplierEdit;
    private javax.swing.JButton jButtontmbhSupplier;
    private javax.swing.JDialog jDialogEditSupplier;
    private javax.swing.JDialog jDialogSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JMenuItem jMenuItemHapus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenuSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSupplier;
    private javax.swing.JTextField jTextFieldKdSupplierOK;
    private javax.swing.JTextField jTextFieldKodeSupplierEdit;
    private javax.swing.JTextField jTextFieldNamaSuplierOk;
    private javax.swing.JTextField jTextFieldNamaSupplierEdit;
    // End of variables declaration//GEN-END:variables

    private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        // model.addColumn("No");
        model.addColumn("Kode Supplier");
        model.addColumn("Nama Supplier");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from datasupplier";
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                Object[]o=new Object[7];
                o[0]= res.getString("kdSupplier");
                o[1]= res.getString("namaSupplier");
                
                model.addRow(o);
            }
            jTableSupplier.setModel(model);
        } catch (Exception e) {
        }
}


    private void clear() {
        jTextFieldKodeSupplierEdit.setText("");
        jTextFieldNamaSupplierEdit.setText("");
        
    }
}
