/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master_Data;

import com.util.FormUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author LENOVO
 */
public class dataUser extends javax.swing.JInternalFrame {

    Connection conn= (Connection)koneksi.configDB();
    /**
     * Creates new form dataBarang1
     */
    public dataUser() {
        initComponents();
        load_table();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogUser = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldnamaUser = new javax.swing.JTextField();
        jTextFieldkdUser = new javax.swing.JTextField();
        jButtonSimpanUser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFielduser = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPopupMenuUser = new javax.swing.JPopupMenu();
        jMenuItemEdit = new javax.swing.JMenuItem();
        jMenuItemHapus = new javax.swing.JMenuItem();
        jDialogEditUser = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNamaUserEdit = new javax.swing.JTextField();
        jTextFieldKodeUserEdit = new javax.swing.JTextField();
        jButtonEditUser = new javax.swing.JButton();
        jTextFieldLevelEdit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFielduserEdit = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableuser = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtontmbhuser = new javax.swing.JButton();

        jDialogUser.setTitle("Tambah User\n");
        jDialogUser.setSize(new java.awt.Dimension(400, 350));

        jLabel1.setText("Kode User");

        jLabel2.setText("Nama User");

        jButtonSimpanUser.setText("Simpan");
        jButtonSimpanUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanUserActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        jLabel4.setText("Level");

        jPasswordFielduser.setText("jPasswordField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kasir" }));

        javax.swing.GroupLayout jDialogUserLayout = new javax.swing.GroupLayout(jDialogUser.getContentPane());
        jDialogUser.getContentPane().setLayout(jDialogUserLayout);
        jDialogUserLayout.setHorizontalGroup(
            jDialogUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogUserLayout.createSequentialGroup()
                        .addGroup(jDialogUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(jDialogUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldkdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldnamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFielduser, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonSimpanUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogUserLayout.setVerticalGroup(
            jDialogUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldkdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDialogUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldnamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDialogUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordFielduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jDialogUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButtonSimpanUser)
                .addGap(32, 32, 32))
        );

        jMenuItemEdit.setText("Edit");
        jMenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditActionPerformed(evt);
            }
        });
        jPopupMenuUser.add(jMenuItemEdit);

        jMenuItemHapus.setText("Hapus");
        jMenuItemHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHapusActionPerformed(evt);
            }
        });
        jPopupMenuUser.add(jMenuItemHapus);

        jDialogEditUser.setTitle("Edit User");
        jDialogEditUser.setSize(new java.awt.Dimension(400, 300));

        jLabel8.setText("Kode User");

        jLabel9.setText("Nama User");

        jButtonEditUser.setText("Edit");
        jButtonEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditUserActionPerformed(evt);
            }
        });

        jLabel5.setText("Password");

        jLabel6.setText("Level");

        jPasswordFielduserEdit.setText("jPasswordField1");

        javax.swing.GroupLayout jDialogEditUserLayout = new javax.swing.GroupLayout(jDialogEditUser.getContentPane());
        jDialogEditUser.getContentPane().setLayout(jDialogEditUserLayout);
        jDialogEditUserLayout.setHorizontalGroup(
            jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditUserLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditUserLayout.createSequentialGroup()
                        .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(43, 43, 43)
                        .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFielduserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLevelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialogEditUserLayout.createSequentialGroup()
                        .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37)
                        .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldKodeUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(jDialogEditUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEditUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogEditUserLayout.setVerticalGroup(
            jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldKodeUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNamaUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordFielduserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldLevelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonEditUser)
                .addContainerGap())
        );

        setTitle("Data User");

        jTableuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableuser.setComponentPopupMenu(jPopupMenuUser);
        jTableuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableuserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableuser);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtontmbhuser.setText("Tambah User");
        jButtontmbhuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontmbhuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtontmbhuser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtontmbhuser)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtontmbhuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontmbhuserActionPerformed
//        FormUtil.centerWindow(jDialogSuplier);
        FormUtil.centerWindow(jDialogUser);
        jDialogUser.setVisible(true);
    }//GEN-LAST:event_jButtontmbhuserActionPerformed

    private void jButtonSimpanUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanUserActionPerformed
        if(jTextFieldkdUser.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Kode User");
        }else if(jTextFieldnamaUser.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Nama User");
        }else if(jPasswordFielduser.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Password");
        }
        else{
            String kduser = jTextFieldkdUser.getText();
            String namauser = jTextFieldnamaUser.getText();
            char[] pwduser = jPasswordFielduserEdit.getPassword();
            String leveluser = jComboBox1.getSelectedItem().toString();
            
            String query ="INSERT INTO `datauser` (`kdUSer`, `namaUser`, `password`, `level`) VALUES ('"+kduser+"', '"+namauser+"', '"+pwduser+"', '"+leveluser+"')";
            try {
                int pilihan = JOptionPane.showConfirmDialog(null, "Simpan data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    clear();
                    load_table();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        clearInput();
    }

    private void load_table1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
    }//GEN-LAST:event_jButtonSimpanUserActionPerformed

    private void jButtonEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditUserActionPerformed
        // TODO add your handling code here:
        if(jTextFieldKodeUserEdit.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Kode User");
        }else if(jTextFieldNamaUserEdit.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Nama User");
        }else if(jTextFieldNamaUserEdit.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Nama User");
        }else if(jTextFieldNamaUserEdit.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Nama User");
        }
        else{
            String kdUser = jTextFieldKodeUserEdit.getText();
            String namaUser = jTextFieldNamaUserEdit.getText();
            String pwd = jPasswordFielduserEdit.getText();
            String level = jTextFieldLevelEdit.getText();
            
            String query ="update `datauser` set `kdUser`= '"+kdUser+"', `namaUser`='"+namaUser+"', `password`='"+pwd+"', `level`='"+level+"' where kdUser = '"+kdUser+"'";
            try {
                int pilihan = JOptionPane.showConfirmDialog(null, "Simpan data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    jDialogEditUser.setVisible(false);
                    jDialogEditUser.dispose();
                    clear();
                    load_table();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
        }
    }//GEN-LAST:event_jButtonEditUserActionPerformed

    private void jTableuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableuserMouseClicked
        // TODO add your handling code here:
        // menampilkan data kedalam form pengisian:
        
        int baris = jTableuser.rowAtPoint(evt.getPoint());
        String kduser =jTableuser.getValueAt(baris, 1).toString();
        jTextFieldKodeUserEdit.setText(kduser);
        
        String query = "SELECT kdUser, namaUser, password, level from datauser where kdUser = '"+kduser+"'";
        try {
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            
            if(res.next()){
                jTextFieldkdUser.setText(res.getString("kdUser"));
                jTextFieldnamaUser.setText(res.getString("namaUser"));
                jPasswordFielduser.setText(res.getString("password"));
                jTextFieldnamaUser.setText(res.getString("level"));
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTableuserMouseClicked

    private void jMenuItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditActionPerformed
        FormUtil.centerWindow(jDialogEditUser);
        jDialogEditUser.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditActionPerformed

    private void jMenuItemHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHapusActionPerformed
        String kduser = jTextFieldkdUser.getText();
        String query_hapus = "delete from datauser where kdUser = '"+kduser+"'";
        try {
            int pilihan = JOptionPane.showConfirmDialog(null, "Hapus data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query_hapus);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    
                    clear();
                    load_table();
                }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jMenuItemHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditUser;
    private javax.swing.JButton jButtonSimpanUser;
    private javax.swing.JButton jButtontmbhuser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialogEditUser;
    private javax.swing.JDialog jDialogUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JMenuItem jMenuItemHapus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFielduser;
    private javax.swing.JPasswordField jPasswordFielduserEdit;
    private javax.swing.JPopupMenu jPopupMenuUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableuser;
    private javax.swing.JTextField jTextFieldKodeUserEdit;
    private javax.swing.JTextField jTextFieldLevelEdit;
    private javax.swing.JTextField jTextFieldNamaUserEdit;
    private javax.swing.JTextField jTextFieldkdUser;
    private javax.swing.JTextField jTextFieldnamaUser;
    // End of variables declaration//GEN-END:variables

    private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Kode User");
        model.addColumn("Nama User");
        model.addColumn("Password");
        model.addColumn("Level");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from datauser";
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                Object[]o=new Object[5];
                o[0]= no++;
                o[1]= res.getString("kdUser");
                o[2]= res.getString("namaUser");
                o[3]= res.getString("password");
                o[4]= res.getString("level");
                
                model.addRow(o);
            }
            jTableuser.setModel(model);
        } catch (Exception e) {
        }
}


    private void clear() {
        jTextFieldKodeUserEdit.setText("");
        jTextFieldNamaUserEdit.setText("");
        jPasswordFielduser.setText("");
    }

    private void clearInput() {
        jTextFieldkdUser.setText("");
        jTextFieldnamaUser.setText("");
        jPasswordFielduser.setText("");
    }
}
