/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master_Data;

import com.util.FormUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author LENOVO
 */
public class dataPelanggan extends javax.swing.JInternalFrame {

    Connection conn= (Connection)koneksi.configDB();
    /**
     * Creates new form dataBarang1
     */
    public dataPelanggan() {
        initComponents();
        load_table();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemEdit = new javax.swing.JMenuItem();
        jMenuItemHapus = new javax.swing.JMenuItem();
        jDialogEdit = new javax.swing.JDialog();
        jLabelKdPelanggan = new javax.swing.JLabel();
        jLabel1NmPelanggan = new javax.swing.JLabel();
        jTextFieldNmPelangganEdit = new javax.swing.JTextField();
        jButtonEditPelangganEdit = new javax.swing.JButton();
        jTextFieldKdPelangganEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPointEdit = new javax.swing.JTextField();
        jDialogTambah = new javax.swing.JDialog();
        jLabelKdPelanggan1 = new javax.swing.JLabel();
        jLabel1NmPelanggan1 = new javax.swing.JLabel();
        jTextFieldNmPelangganTambah = new javax.swing.JTextField();
        jButtonTambahPelanggan1 = new javax.swing.JButton();
        jTextFieldKdPelangganTambah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPoint = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePelanggan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtontmbhPelanggan = new javax.swing.JButton();

        jMenuItemEdit.setText("Edit");
        jMenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemEdit);

        jMenuItemHapus.setText("Hapus");
        jMenuItemHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHapusActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemHapus);

        jDialogEdit.setTitle("Edit Pelanggan");
        jDialogEdit.setSize(new java.awt.Dimension(400, 350));

        jLabelKdPelanggan.setText("Kode Pelanggan");

        jLabel1NmPelanggan.setText("Nama Pelanggan ");

        jButtonEditPelangganEdit.setText("Edit");
        jButtonEditPelangganEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPelangganEditActionPerformed(evt);
            }
        });

        jTextFieldKdPelangganEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKdPelangganEditActionPerformed(evt);
            }
        });

        jLabel2.setText("Point");

        javax.swing.GroupLayout jDialogEditLayout = new javax.swing.GroupLayout(jDialogEdit.getContentPane());
        jDialogEdit.getContentPane().setLayout(jDialogEditLayout);
        jDialogEditLayout.setHorizontalGroup(
            jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelKdPelanggan)
                        .addComponent(jLabel1NmPelanggan)
                        .addComponent(jLabel2))
                    .addGroup(jDialogEditLayout.createSequentialGroup()
                        .addComponent(jButtonEditPelangganEdit)
                        .addGap(49, 49, 49)))
                .addGap(41, 41, 41)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNmPelangganEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jTextFieldKdPelangganEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jTextFieldPointEdit))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jDialogEditLayout.setVerticalGroup(
            jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKdPelanggan)
                    .addComponent(jTextFieldKdPelangganEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1NmPelanggan)
                    .addComponent(jTextFieldNmPelangganEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPointEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonEditPelangganEdit)
                .addGap(23, 23, 23))
        );

        jDialogTambah.setTitle("Tambah Pelanggan");
        jDialogTambah.setSize(new java.awt.Dimension(400, 400));

        jLabelKdPelanggan1.setText("Kode Pelanggan");

        jLabel1NmPelanggan1.setText("Nama Pelanggan ");

        jButtonTambahPelanggan1.setText("Tambah");
        jButtonTambahPelanggan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahPelanggan1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Point");

        javax.swing.GroupLayout jDialogTambahLayout = new javax.swing.GroupLayout(jDialogTambah.getContentPane());
        jDialogTambah.getContentPane().setLayout(jDialogTambahLayout);
        jDialogTambahLayout.setHorizontalGroup(
            jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonTambahPelanggan1)
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogTambahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKdPelanggan1)
                    .addComponent(jLabel1NmPelanggan1)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNmPelangganTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jTextFieldKdPelangganTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jTextFieldPoint))
                .addGap(36, 36, 36))
        );
        jDialogTambahLayout.setVerticalGroup(
            jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTambahLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKdPelanggan1)
                    .addComponent(jTextFieldKdPelangganTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1NmPelanggan1)
                    .addComponent(jTextFieldNmPelangganTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButtonTambahPelanggan1)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jTextPane1);

        setTitle("Data Pelanggan");

        jTablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePelanggan.setComponentPopupMenu(jPopupMenu1);
        jTablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePelanggan);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtontmbhPelanggan.setText("Tambah Pelanggan");
        jButtontmbhPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontmbhPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtontmbhPelanggan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtontmbhPelanggan)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtontmbhPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontmbhPelangganActionPerformed
        FormUtil.centerWindow(jDialogTambah);
        jDialogTambah.setVisible(true);
    }//GEN-LAST:event_jButtontmbhPelangganActionPerformed

    private void jButtonEditPelangganEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPelangganEditActionPerformed
        // TODO add your handling code here:
        if(jTextFieldKdPelangganEdit.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Kode Pelanggan");
        }else if(jTextFieldNmPelangganEdit.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Nama Pelanggan");
        }else if(jTextFieldPointEdit.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Jumlah Point");
        }
        else{
            String KdPlnggn = jTextFieldKdPelangganEdit.getText();
            String namaPlnggn = jTextFieldNmPelangganEdit.getText();
            String point = jTextFieldPointEdit.getText();
            
            String query ="update `datapelanggan` set `kdPelanggan`= '"+KdPlnggn+"', `namaPelanggan`='"+namaPlnggn+"', `Point` ='"+point+"' where kdPelanggan = '"+KdPlnggn+"'";
            try {
                int pilihan = JOptionPane.showConfirmDialog(null, "Simpan data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    jDialogEdit.setVisible(false);
                    jDialogEdit.dispose();
                    clear();
                    load_table();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
        }
    }//GEN-LAST:event_jButtonEditPelangganEditActionPerformed

    private void jTablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePelangganMouseClicked
        // TODO add your handling code here:
        // menampilkan data kedalam form pengisian:
        
        int baris = jTablePelanggan.rowAtPoint(evt.getPoint());
        String kdPelanggan =jTablePelanggan.getValueAt(baris,1 ).toString();
        jTextFieldKdPelangganEdit.setText(kdPelanggan);
        
        String query = "SELECT kdPelanggan, namaPelanggan, Point from dataPelanggan where kdPelanggan = '"+kdPelanggan+"'";
        try {
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            
            if(res.next()){
                jTextFieldNmPelangganEdit.setText(res.getString("namaPelanggan"));
                jTextFieldKdPelangganEdit.setText(res.getString("kdPelanggan"));
                jTextFieldPointEdit.setText(res.getString("Point"));
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTablePelangganMouseClicked

    private void jMenuItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditActionPerformed
        FormUtil.centerWindow(jDialogEdit);
        jDialogEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditActionPerformed

    private void jMenuItemHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHapusActionPerformed
        String kdPelanggan = jTextFieldKdPelangganEdit.getText();
        String query_hapus = "delete from dataPelanggan where kdPelanggan = '"+kdPelanggan+"'";
        try {
            int pilihan = JOptionPane.showConfirmDialog(null, "Hapus data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query_hapus);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    
                    clear();
                    load_table();
                }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jMenuItemHapusActionPerformed

    private void jButtonTambahPelanggan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahPelanggan1ActionPerformed
        // TODO add your handling code here:
         if(jTextFieldKdPelangganTambah.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Kode Pelanggan");
        }else if(jTextFieldNmPelangganTambah.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Nama Pelanggan");
        }else if(jTextFieldPoint.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Jumlah Point");
        }
        else{
            String KdPlnggn = jTextFieldKdPelangganTambah.getText();
            String namaPlnggn = jTextFieldNmPelangganTambah.getText();
            String point = jTextFieldPoint.getText();
            
            String query ="insert into `datapelanggan`(kdPelanggan,namaPelanggan,Point) values ( '"+KdPlnggn+"', '"+namaPlnggn+"', '"+point+"')";
            try {
                int pilihan = JOptionPane.showConfirmDialog(null, "Simpan data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    jDialogTambah.setVisible(false);
                    jDialogTambah.dispose();
                    clear();
                    load_table();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
        }
        
    }//GEN-LAST:event_jButtonTambahPelanggan1ActionPerformed

    private void jTextFieldKdPelangganEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKdPelangganEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKdPelangganEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditPelangganEdit;
    private javax.swing.JButton jButtonTambahPelanggan1;
    private javax.swing.JButton jButtontmbhPelanggan;
    private javax.swing.JDialog jDialogEdit;
    private javax.swing.JDialog jDialogTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1NmPelanggan;
    private javax.swing.JLabel jLabel1NmPelanggan1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelKdPelanggan;
    private javax.swing.JLabel jLabelKdPelanggan1;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JMenuItem jMenuItemHapus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePelanggan;
    private javax.swing.JTextField jTextFieldKdPelangganEdit;
    private javax.swing.JTextField jTextFieldKdPelangganTambah;
    private javax.swing.JTextField jTextFieldNmPelangganEdit;
    private javax.swing.JTextField jTextFieldNmPelangganTambah;
    private javax.swing.JTextField jTextFieldPoint;
    private javax.swing.JTextField jTextFieldPointEdit;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Kode Pelanggan");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Point");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from datapelanggan";
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                Object[]o=new Object[4];
                o[0]= no++;
                o[1]= res.getString("kdPelanggan");
                o[2]= res.getString("namaPelanggan");
                o[3]= res.getString("Point");
                
                model.addRow(o);
            }
            jTablePelanggan.setModel(model);
        } catch (Exception e) {
        }
}

    
       private void clear() {
        jTextFieldKdPelangganEdit.setText("");
        jTextFieldNmPelangganEdit.setText("");
        jTextFieldPoint.setText("");
        
    }
}
