/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master_Data;

import com.util.FormUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author LENOVO
 */
public class dataBarang1 extends javax.swing.JInternalFrame {

    Connection conn= (Connection)koneksi.configDB();
    /**
     * Creates new form dataBarang1
     */
    public dataBarang1() {
        initComponents();
        load_table();
        
        tampil_comboSatuan();
        tampil_kategori();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDataBarang = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNamaBarang = new javax.swing.JTextField();
        jTextFieldBarcode = new javax.swing.JTextField();
        jComboBoxSatuan = new javax.swing.JComboBox<>();
        jComboBoxKategori = new javax.swing.JComboBox<>();
        jFormattedTextField_Hrg_Beli = new javax.swing.JFormattedTextField();
        jFormattedTextField_HrgJual = new javax.swing.JFormattedTextField();
        jFormattedTextField_Stok = new javax.swing.JFormattedTextField();
        jButtonSimpan = new javax.swing.JButton();
        jTextFieldkdSatuan = new javax.swing.JTextField();
        jTextFieldkdKategori = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemEdit = new javax.swing.JMenuItem();
        jMenuItemHapus = new javax.swing.JMenuItem();
        jDialogEdit = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNamaBarang1 = new javax.swing.JTextField();
        jTextFieldBarcode1 = new javax.swing.JTextField();
        jComboBoxSatuan1 = new javax.swing.JComboBox<>();
        jComboBoxKategori1 = new javax.swing.JComboBox<>();
        jFormattedTextField_Hrg_Beli1 = new javax.swing.JFormattedTextField();
        jFormattedTextField_HrgJual1 = new javax.swing.JFormattedTextField();
        jFormattedTextField_Stok1 = new javax.swing.JFormattedTextField();
        jButtonEdit = new javax.swing.JButton();
        jTextFieldkdSatuan1 = new javax.swing.JTextField();
        jTextFieldkdKategori1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledataBarang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtontmbhBarang = new javax.swing.JButton();

        jDialogDataBarang.setTitle("Tambah Barang");
        jDialogDataBarang.setSize(new java.awt.Dimension(400, 600));

        jLabel1.setText("Barcode");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Kategori");

        jLabel4.setText("Satuan");

        jLabel5.setText("Hrg Beli");

        jLabel6.setText("Hrg Jual");

        jLabel7.setText("Stock");

        jComboBoxSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pcs", "Dus", "Kantong", "Pak", "Kilogram", " " }));
        jComboBoxSatuan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxSatuanItemStateChanged(evt);
            }
        });

        jComboBoxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxKategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxKategoriItemStateChanged(evt);
            }
        });

        jFormattedTextField_Hrg_Beli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jFormattedTextField_HrgJual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jFormattedTextField_Stok.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogDataBarangLayout = new javax.swing.GroupLayout(jDialogDataBarang.getContentPane());
        jDialogDataBarang.getContentPane().setLayout(jDialogDataBarangLayout);
        jDialogDataBarangLayout.setHorizontalGroup(
            jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogDataBarangLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonSimpan)
                        .addGap(118, 118, 118))
                    .addGroup(jDialogDataBarangLayout.createSequentialGroup()
                        .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogDataBarangLayout.createSequentialGroup()
                                .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextField_Hrg_Beli)
                                    .addComponent(jFormattedTextField_HrgJual)
                                    .addComponent(jFormattedTextField_Stok)
                                    .addGroup(jDialogDataBarangLayout.createSequentialGroup()
                                        .addComponent(jComboBoxSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldkdSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDialogDataBarangLayout.createSequentialGroup()
                                        .addComponent(jComboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldkdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(152, Short.MAX_VALUE))
                            .addGroup(jDialogDataBarangLayout.createSequentialGroup()
                                .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jDialogDataBarangLayout.setVerticalGroup(
            jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldkdSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldkdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextField_Hrg_Beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextField_HrgJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextField_Stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButtonSimpan)
                .addGap(46, 46, 46))
        );

        jMenuItemEdit.setText("Edit");
        jMenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemEdit);

        jMenuItemHapus.setText("Hapus");
        jMenuItemHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHapusActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemHapus);

        jDialogEdit.setTitle("Edit Barang");
        jDialogEdit.setSize(new java.awt.Dimension(400, 600));

        jLabel8.setText("Barcode");

        jLabel9.setText("Nama Barang");

        jLabel10.setText("Kategori");

        jLabel11.setText("Satuan");

        jLabel12.setText("Hrg Beli");

        jLabel13.setText("Hrg Jual");

        jLabel14.setText("Stock");

        jComboBoxSatuan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pcs", "Dus", "Kantong", "Pak", "Kilogram", " " }));
        jComboBoxSatuan1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxSatuan1ItemStateChanged(evt);
            }
        });

        jComboBoxKategori1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxKategori1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxKategori1ItemStateChanged(evt);
            }
        });

        jFormattedTextField_Hrg_Beli1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jFormattedTextField_HrgJual1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jFormattedTextField_Stok1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogEditLayout = new javax.swing.GroupLayout(jDialogEdit.getContentPane());
        jDialogEdit.getContentPane().setLayout(jDialogEditLayout);
        jDialogEditLayout.setHorizontalGroup(
            jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonEdit)
                        .addGap(118, 118, 118))
                    .addGroup(jDialogEditLayout.createSequentialGroup()
                        .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37)
                        .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogEditLayout.createSequentialGroup()
                                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextField_Hrg_Beli1)
                                    .addComponent(jFormattedTextField_HrgJual1)
                                    .addComponent(jFormattedTextField_Stok1)
                                    .addGroup(jDialogEditLayout.createSequentialGroup()
                                        .addComponent(jComboBoxSatuan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldkdSatuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDialogEditLayout.createSequentialGroup()
                                        .addComponent(jComboBoxKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldkdKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(152, Short.MAX_VALUE))
                            .addGroup(jDialogEditLayout.createSequentialGroup()
                                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNamaBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBarcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jDialogEditLayout.setVerticalGroup(
            jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldBarcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldNamaBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxSatuan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldkdSatuan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldkdKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jFormattedTextField_Hrg_Beli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jFormattedTextField_HrgJual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jFormattedTextField_Stok1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButtonEdit)
                .addGap(46, 46, 46))
        );

        setTitle("Data Barang");

        jTabledataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabledataBarang.setComponentPopupMenu(jPopupMenu1);
        jTabledataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabledataBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabledataBarang);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtontmbhBarang.setText("Tambah Barang");
        jButtontmbhBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontmbhBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtontmbhBarang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtontmbhBarang)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtontmbhBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontmbhBarangActionPerformed
        FormUtil.centerWindow(jDialogDataBarang);
        jDialogDataBarang.setVisible(true);
    }//GEN-LAST:event_jButtontmbhBarangActionPerformed

    private void jComboBoxSatuan1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxSatuan1ItemStateChanged
        // TODO add your handling code here:
         try {
            if(jComboBoxSatuan1.getSelectedIndex()==0){
                jTextFieldkdSatuan1.setText("");
            }else{
                String namaSatuan = jComboBoxSatuan1.getSelectedItem().toString();
                String query = "select kdSatuan from tabelsatuan where namaSatuan = '"+namaSatuan+"'";

                try {
                    Statement stm=conn.createStatement();
                    ResultSet rs=stm.executeQuery(query);

                    if(rs.next()){
                        jTextFieldkdSatuan1.setText(rs.getString("kdSatuan"));
                    }
                } catch (Exception e) {
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBoxSatuan1ItemStateChanged

    private void jComboBoxKategori1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxKategori1ItemStateChanged
        // TODO add your handling code here:
        try {
            if(jComboBoxKategori1.getSelectedIndex()==0){
                jTextFieldkdKategori1.setText("");
            }else{
                String namaKategori = jComboBoxKategori1.getSelectedItem().toString();
                String query = "select kdKategori from tabelkategori where namaKategori = '"+namaKategori+"'";

                try {
                    Statement stm=conn.createStatement();
                    ResultSet rs=stm.executeQuery(query);

                    if(rs.next()){
                        jTextFieldkdKategori1.setText(rs.getString("kdKategori"));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jComboBoxKategori1ItemStateChanged

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        if(jTextFieldBarcode1.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Kode Barang");
        }else if(jTextFieldNamaBarang1.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Nama Barang");
        }else if(jComboBoxSatuan1.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Pilih Satuan");
        }else if(jComboBoxKategori1.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Pilih Kategori");
        }else if(jFormattedTextField_Hrg_Beli1.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Harga Beli Barang");
        }else if(jFormattedTextField_HrgJual1.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Harga Jual Barang");
        }else if(jFormattedTextField_Stok1.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Stok Barang");
        }else{
            String barcode = jTextFieldBarcode1.getText();
            String namabrg = jTextFieldNamaBarang1.getText();
            String kdSatuan = jTextFieldkdSatuan1.getText();
            String kdKategori = jTextFieldkdKategori1.getText();
            
            String hrg_b = jFormattedTextField_Hrg_Beli1.getText();
            String hb = hrg_b.replace(",", "");
            double hrgBeli = Double.valueOf(hb);
            
            String hrg_j = jFormattedTextField_HrgJual1.getText();
            String hj = hrg_j.replace(",", "");
            double hrgJual = Double.valueOf(hj);
            
            String stok = jFormattedTextField_Stok1.getText();
            String stoka = stok.replace(",", "");
            double stokOke = Double.valueOf(stoka);
            
            String query ="update `databarang` set `namaBarang`= '"+namabrg+"', `kdSatuan`='"+kdSatuan+"', `kdKategori`='"+kdKategori+"', `hrgBeli`='"+hrgBeli+"', `hrgJual`='"+hrgJual+"', `stok`= '"+stokOke+"' where barcode = '"+barcode+"'";
            try {
                int pilihan = JOptionPane.showConfirmDialog(null, "Simpan data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    jDialogEdit.setVisible(false);
                    jDialogEdit.dispose();
                    clear();
                    load_table();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jTabledataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabledataBarangMouseClicked
        // TODO add your handling code here:
        // menampilkan data kedalam form pengisian:
        
        int baris = jTabledataBarang.rowAtPoint(evt.getPoint());
        String barcode =jTabledataBarang.getValueAt(baris, 0).toString();
        jTextFieldBarcode1.setText(barcode);
        
        String query = "SELECT namaBarang, namaSatuan,databarang.kdSatuan, namaKategori,databarang.kdKategori, hrgBeli,hrgJual, stok from databarang, tabelsatuan, tabelkategori where databarang.kdSatuan = tabelsatuan.kdSatuan AND databarang.kdKategori = tabelkategori.kdKategori AND databarang.barcode = '"+barcode+"'";
        try {
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            
            if(res.next()){
                jTextFieldNamaBarang1.setText(res.getString("namaBarang"));
                jTextFieldkdSatuan1.setText(res.getString("kdSatuan"));
                jComboBoxSatuan1.setSelectedItem(res.getString("namaSatuan"));
                jComboBoxKategori1.setSelectedItem(res.getString("namaKategori"));
                jTextFieldkdKategori1.setText(res.getString("kdKategori"));
                double hrgBeli = Double.parseDouble(res.getString("hrgBeli"));
                jFormattedTextField_Hrg_Beli1.setText(String.format("%,.2f", hrgBeli));
                double hrgjual = Double.parseDouble(res.getString("hrgJual"));
                jFormattedTextField_HrgJual1.setText(String.format("%,.2f", hrgjual));
                double stok = Double.parseDouble(res.getString("stok"));
                jFormattedTextField_Stok1.setText(String.format("%,.2f", stok));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTabledataBarangMouseClicked

    private void jMenuItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditActionPerformed
        FormUtil.centerWindow(jDialogEdit);
        jDialogEdit.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditActionPerformed

    private void jMenuItemHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHapusActionPerformed
        String barcode = jTextFieldBarcode1.getText();
        String query_hapus = "delete from databarang where barcode = '"+barcode+"'";
        try {
            int pilihan = JOptionPane.showConfirmDialog(null, "Hapus data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query_hapus);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    
                    clear();
                    load_table();
                }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jMenuItemHapusActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        if(jTextFieldBarcode.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Kode Barang");
        }else if(jTextFieldNamaBarang.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Nama Barang");
        }else if(jComboBoxSatuan.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Pilih Satuan");
        }else if(jComboBoxKategori.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Pilih Kategori");
        }else if(jFormattedTextField_Hrg_Beli.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Harga Beli Barang");
        }else if(jFormattedTextField_HrgJual.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Harga Jual Barang");
        }else if(jFormattedTextField_Stok.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Masukan Stok Barang");
        }else{
            String barcode = jTextFieldBarcode.getText();
            String namabrg = jTextFieldNamaBarang.getText();
            String kdSatuan = jTextFieldkdSatuan.getText();
            String kdKategori = jTextFieldkdKategori.getText();

            String hrg_b = jFormattedTextField_Hrg_Beli.getText();
            String hb = hrg_b.replace(",", "");
            double hrgBeli = Double.valueOf(hb);

            String hrg_j = jFormattedTextField_HrgJual.getText();
            String hj = hrg_j.replace(",", "");
            double hrgJual = Double.valueOf(hj);

            String stok = jFormattedTextField_Stok.getText();
            String stoka = stok.replace(",", "");
            double stokOke = Double.valueOf(stoka);

            String query ="INSERT INTO `databarang` (`barcode`, `namaBarang`, `kdSatuan`, `kdKategori`, `hrgBeli`, `hrgJual`, `stok`) VALUES ('"+barcode+"', '"+namabrg+"', '"+kdSatuan+"', '"+kdKategori+"', '"+hrgBeli+"', '"+hrgJual+"', '"+stokOke+"')";
            try {
                int pilihan = JOptionPane.showConfirmDialog(null, "Simpan data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if(pilihan==JOptionPane.YES_OPTION){
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    clear();
                    load_table();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jComboBoxKategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxKategoriItemStateChanged
        try {
            if(jComboBoxKategori.getSelectedIndex()==0){
                jTextFieldkdKategori.setText("");
            }else{
                String namaKategori = jComboBoxKategori.getSelectedItem().toString();
                String query = "select kdKategori from tabelkategori where namaKategori = '"+namaKategori+"'";

                try {
                    Statement stm=conn.createStatement();
                    ResultSet rs=stm.executeQuery(query);

                    if(rs.next()){
                        jTextFieldkdKategori.setText(rs.getString("kdKategori"));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBoxKategoriItemStateChanged

    private void jComboBoxSatuanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxSatuanItemStateChanged
        try {
            if(jComboBoxSatuan.getSelectedIndex()==0){
                jTextFieldkdSatuan.setText("");
            }else{
                String namaSatuan = jComboBoxSatuan.getSelectedItem().toString();
                String query = "select kdSatuan from tabelsatuan where namaSatuan = '"+namaSatuan+"'";

                try {
                    Statement stm=conn.createStatement();
                    ResultSet rs=stm.executeQuery(query);

                    if(rs.next()){
                        jTextFieldkdSatuan.setText(rs.getString("kdSatuan"));
                    }
                } catch (Exception e) {
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBoxSatuanItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtontmbhBarang;
    private javax.swing.JComboBox<String> jComboBoxKategori;
    private javax.swing.JComboBox<String> jComboBoxKategori1;
    private javax.swing.JComboBox<String> jComboBoxSatuan;
    private javax.swing.JComboBox<String> jComboBoxSatuan1;
    private javax.swing.JDialog jDialogDataBarang;
    private javax.swing.JDialog jDialogEdit;
    private javax.swing.JFormattedTextField jFormattedTextField_HrgJual;
    private javax.swing.JFormattedTextField jFormattedTextField_HrgJual1;
    private javax.swing.JFormattedTextField jFormattedTextField_Hrg_Beli;
    private javax.swing.JFormattedTextField jFormattedTextField_Hrg_Beli1;
    private javax.swing.JFormattedTextField jFormattedTextField_Stok;
    private javax.swing.JFormattedTextField jFormattedTextField_Stok1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JMenuItem jMenuItemHapus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabledataBarang;
    private javax.swing.JTextField jTextFieldBarcode;
    private javax.swing.JTextField jTextFieldBarcode1;
    private javax.swing.JTextField jTextFieldNamaBarang;
    private javax.swing.JTextField jTextFieldNamaBarang1;
    private javax.swing.JTextField jTextFieldkdKategori;
    private javax.swing.JTextField jTextFieldkdKategori1;
    private javax.swing.JTextField jTextFieldkdSatuan;
    private javax.swing.JTextField jTextFieldkdSatuan1;
    // End of variables declaration//GEN-END:variables
private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
//        model.addColumn("No");
        model.addColumn("Barcode");
        model.addColumn("Nama Barang");
        model.addColumn("Satuan");
        model.addColumn("Kategori");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from databarang";
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                Object[]o=new Object[7];
                o[0]= res.getString("barcode");
                o[1]= res.getString("namaBarang");
                o[2]= res.getString("kdSatuan");
                o[3]= res.getString("kdKategori");
                double j = Double.parseDouble(res.getString("hrgBeli"));
                o[4]= String.format("%,.2f", j);
                double k = Double.parseDouble(res.getString("hrgJual"));
                o[5]= String.format("%,.2f", k);
                double l = Double.parseDouble(res.getString("stok"));
                o[6]= String.format("%,.2f", l);
//                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),});
                model.addRow(o);
            }
            jTabledataBarang.setModel(model);
        } catch (Exception e) {
        }
}

    private void tampil_comboSatuan() {
         jComboBoxSatuan.removeAllItems();
         jComboBoxSatuan.addItem("Pilih Satuan");
         jComboBoxSatuan1.removeAllItems();
         jComboBoxSatuan1.addItem("Pilih Satuan");
         String query = "select namaSatuan from tabelsatuan order by namaSatuan asc";
         try {
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
             while (res.next()) {                 
                 jComboBoxSatuan.addItem(res.getString("namaSatuan"));
                 jComboBoxSatuan1.addItem(res.getString("namaSatuan"));
             }
             res.last();
             int jumlahData = res.getRow();
             res.first();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }

    
    }

    private void tampil_kategori() {
         jComboBoxKategori.removeAllItems();
         jComboBoxKategori.addItem("Pilih Kategori");
         jComboBoxKategori1.removeAllItems();
         jComboBoxKategori1.addItem("Pilih Kategori");
         String query = "select namaKategori from tabelkategori order by namakategori asc";
         try {
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
             while (res.next()) {                 
                 jComboBoxKategori.addItem(res.getString("namaKategori"));
                 jComboBoxKategori1.addItem(res.getString("namaKategori"));
             }
             res.last();
             int jumlahData = res.getRow();
             res.first();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void clear() {
        jTextFieldBarcode.setText("");
        jTextFieldNamaBarang.setText("");
        jComboBoxSatuan.setSelectedIndex(0);
        jComboBoxKategori.setSelectedIndex(0);
        jFormattedTextField_Hrg_Beli.setText("");
        jFormattedTextField_HrgJual.setText("");
        jFormattedTextField_Stok.setText("");
        
        jTextFieldBarcode1.setText("");
        jTextFieldNamaBarang1.setText("");
        jComboBoxSatuan1.setSelectedIndex(0);
        jComboBoxKategori1.setSelectedIndex(0);
        jFormattedTextField_Hrg_Beli1.setText("");
        jFormattedTextField_HrgJual1.setText("");
        jFormattedTextField_Stok1.setText("");
    }
}
