/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pembelian;

import com.util.FormUtil;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;

/**
 *
 * @author LENOVO
 */
public class Pembelian extends javax.swing.JInternalFrame {

    Connection conn = (Connection)koneksi.configDB();
    JasperReport JR;
    JasperPrint JP;
    Map<String, Object> param = new HashMap<String, Object >(2);
    JasperDesign JD;
    /**
     * Creates new form Pembelian
     */
    public Pembelian() {
        initComponents();
        tampilNamaFaktur();
        tampil_supplier();
        load_tabelBeli();
        tampil_total();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogCariBarang = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCari = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldCariBarang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxsupplier = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldkdSupplier = new javax.swing.JTextField();
        jLabeltotalBeli = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldnoFakturPembelian = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtBarcode = new javax.swing.JTextField();
        txtnmBarang = new javax.swing.JTextField();
        jTextFieldhrgJual = new javax.swing.JTextField();
        jFormattedTextFieldhrgBeli = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldjmlBeli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPembelian = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnSimpanpembelian = new javax.swing.JButton();
        btnCariBarangpembelian = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldBayarpembelian = new javax.swing.JFormattedTextField();
        jFormattedTextFieldKembaliPembelian = new javax.swing.JFormattedTextField();

        jDialogCariBarang.setSize(new java.awt.Dimension(800, 500));

        jTableCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCariMouseClicked(evt);
            }
        });
        jTableCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableCariKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCari);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 2));

        jTextFieldCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCariBarangActionPerformed(evt);
            }
        });
        jTextFieldCariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCariBarangKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCariBarangKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Masukan Nama Barang ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(47, 47, 47)
                .addComponent(jTextFieldCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jDialogCariBarangLayout = new javax.swing.GroupLayout(jDialogCariBarang.getContentPane());
        jDialogCariBarang.getContentPane().setLayout(jDialogCariBarangLayout);
        jDialogCariBarangLayout.setHorizontalGroup(
            jDialogCariBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jDialogCariBarangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogCariBarangLayout.setVerticalGroup(
            jDialogCariBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCariBarangLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        setTitle("Form Pembelian ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Pilih Supplier");

        jComboBoxsupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxsupplier.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxsupplierItemStateChanged(evt);
            }
        });

        jLabel2.setText("Kode Supplier");

        jLabeltotalBeli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setText("No Faktur Pembelian");

        jTextFieldnoFakturPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnoFakturPembelianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldnoFakturPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldkdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabeltotalBeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldnoFakturPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextFieldkdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addGap(8, 8, 8))
                    .addComponent(jLabeltotalBeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyPressed(evt);
            }
        });

        jLabel3.setText("JML");

        jTextFieldjmlBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldjmlBeliKeyPressed(evt);
            }
        });

        jLabel4.setText("Barcode");

        jLabel5.setText("Nama Barang");

        jLabel10.setText("Hrg_lual");

        jLabel6.setText("Hrg_Beli");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtnmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldhrgJual, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldhrgBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldjmlBeli))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldhrgBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldjmlBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldhrgJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabelPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPembelian);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSimpanpembelian.setText("Simpan");
        btnSimpanpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanpembelianActionPerformed(evt);
            }
        });

        btnCariBarangpembelian.setText("Cari Barang");
        btnCariBarangpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBarangpembelianActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("BAYAR");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("KEMBALI");

        jFormattedTextFieldBayarpembelian.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedTextFieldBayarpembelian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFormattedTextFieldBayarpembelian.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jFormattedTextFieldBayarpembelianCaretUpdate(evt);
            }
        });
        jFormattedTextFieldBayarpembelian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldBayarpembelianKeyPressed(evt);
            }
        });

        jFormattedTextFieldKembaliPembelian.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedTextFieldKembaliPembelian.setEnabled(false);
        jFormattedTextFieldKembaliPembelian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCariBarangpembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpanpembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextFieldKembaliPembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldBayarpembelian))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpanpembelian)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jFormattedTextFieldBayarpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jFormattedTextFieldKembaliPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCariBarangpembelian))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            String barcode = txtBarcode.getText();
            String query = "select namaBarang,hrgJual,hrgBeli from databarang where barcode ='"+barcode+"'";
            
            try {
                Statement stm=conn.createStatement();
                ResultSet rs=stm.executeQuery(query);

                if(rs.next()){
                    txtnmBarang.setText(rs.getString("namaBarang"));

                    double hrgJual = Double.parseDouble(rs.getString("hrgJual"));
                    jTextFieldhrgJual.setText(String.format("%,.2f", hrgJual));

                    double hrgBeli = Double.parseDouble(rs.getString("hrgBeli"));
                    jFormattedTextFieldhrgBeli.setText(String.format("%,.2f", hrgBeli));

                    jFormattedTextFieldhrgBeli.requestFocus();
                } else {
                    txtnmBarang.setText("");
                    jTextFieldhrgJual.setText("0");

                    txtBarcode.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_txtBarcodeKeyPressed

    private void btnSimpanpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanpembelianActionPerformed
        // TODO add your handling code here:
//        simpan();
    }//GEN-LAST:event_btnSimpanpembelianActionPerformed

    private void btnCariBarangpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBarangpembelianActionPerformed
        // TODO add your handling code here:
        FormUtil.centerWindow(jDialogCariBarang);
        jDialogCariBarang.setVisible(true);
        //load_table();
    }//GEN-LAST:event_btnCariBarangpembelianActionPerformed

    private void jFormattedTextFieldBayarpembelianCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jFormattedTextFieldBayarpembelianCaretUpdate
        // TODO add your handling code here:
        if(jFormattedTextFieldBayarpembelian.getText().length()==0){

        }else{
            String bayar = jFormattedTextFieldBayarpembelian.getText();
            String bayarOke = bayar.replace(",", "");
            double pembayaran = Double.valueOf(bayarOke);
            String total = jLabeltotalBeli.getText();
            String totalbayar = total.replace(",", "");
            double totalFormat = Double.valueOf(totalbayar);

            double kembali = pembayaran - totalFormat;
            jFormattedTextFieldKembaliPembelian.setText(String.format("%,.2f", kembali));

        }
    }//GEN-LAST:event_jFormattedTextFieldBayarpembelianCaretUpdate

    private void jFormattedTextFieldBayarpembelianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldBayarpembelianKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            simpan();

        }
    }//GEN-LAST:event_jFormattedTextFieldBayarpembelianKeyPressed

    private void jTextFieldnoFakturPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnoFakturPembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnoFakturPembelianActionPerformed

    private void jComboBoxsupplierItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxsupplierItemStateChanged
        // TODO add your handling code here:
        try {
            if(jComboBoxsupplier.getSelectedIndex()==0){
                jTextFieldkdSupplier.setText("");
            }else{
                String namaSupplier = jComboBoxsupplier.getSelectedItem().toString();
                String query = "select kdSupplier from datasupplier where namaSupplier = '"+namaSupplier+"'";

                try {
                    Statement stm=conn.createStatement();
                    ResultSet rs=stm.executeQuery(query);

                    if(rs.next()){
                        jTextFieldkdSupplier.setText(rs.getString("kdSupplier"));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBoxsupplierItemStateChanged

    private void jTableCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCariMouseClicked
        // TODO add your handling code here:
        int baris = jTableCari.rowAtPoint(evt.getPoint());
        String barcode =jTableCari.getValueAt(baris, 0).toString();
        txtBarcode.setText(barcode);

        String query = "select namaBarang,hrgJual,hrgBeli from databarang where barcode ='"+barcode+"'";
        try {
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery(query);

            if(rs.next()){
                txtnmBarang.setText(rs.getString("namaBarang"));
                double hrgJual = Double.parseDouble(rs.getString("hrgJual"));
                jTextFieldhrgJual.setText(String.format("%,.2f", hrgJual));

                double hrgBeli = Double.parseDouble(rs.getString("hrgBeli"));
                jFormattedTextFieldhrgBeli.setText(String.format("%,.2f", hrgBeli));

                jDialogCariBarang.setVisible(false);
                jDialogCariBarang.dispose();

                jTextFieldjmlBeli.requestFocus();
            }else {
                txtnmBarang.setText("");
                jTextFieldhrgJual.setText("0");

                txtBarcode.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTableCariMouseClicked

    private void jTableCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCariKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:

        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {

            String barcode =txtBarcode.getText();
            String query = "select namaBarang,hrgJual,hrgBeli from databarang where barcode ='"+barcode+"'";
            try {
                Statement stm=conn.createStatement();
                ResultSet rs=stm.executeQuery(query);

                if(rs.next()){
                    txtnmBarang.setText(rs.getString("namaBarang"));
                    double hrgJual = Double.parseDouble(rs.getString("hrgJual"));
                    jTextFieldhrgJual.setText(String.format("%,.2f", hrgJual));

                    double hrgBeli = Double.parseDouble(rs.getString("hrgBeli"));
                    jFormattedTextFieldhrgBeli.setText(String.format("%,.2f", hrgBeli));

                    jDialogCariBarang.setVisible(false);
                    jDialogCariBarang.dispose();

                    jTextFieldjmlBeli.requestFocus();
                }else {
                    txtnmBarang.setText("");
                    jTextFieldhrgJual.setText("0");

                    txtBarcode.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_jTableCariKeyPressed

    private void jTextFieldCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCariBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCariBarangActionPerformed

    private void jTextFieldCariBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCariBarangKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTableCari.getSelectionModel().addSelectionInterval(0, 0);
            jTableCari.requestFocus();

        }
    }//GEN-LAST:event_jTextFieldCariBarangKeyPressed

    private void jTextFieldCariBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCariBarangKeyReleased
        // TODO add your handling code here:
//        load_table();

    }//GEN-LAST:event_jTextFieldCariBarangKeyReleased

    private void jTextFieldjmlBeliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldjmlBeliKeyPressed
        // TODO add your handling code here:
           if (evt.getKeyCode()==KeyEvent.VK_ENTER) {

            String nofakbeli = jTextFieldnoFakturPembelian.getText();
            String barcode = txtBarcode.getText();
            String jmlBeli = jTextFieldjmlBeli.getText();
            String jmla = jmlBeli.replace(",", "");
            double jumlah = Double.valueOf(jmla);

            String namaBarang = txtnmBarang.getText();

            String hrgjual = jTextFieldhrgJual.getText();
            String hrgjuala = hrgjual.replace(",", "");
            double hrgjualOk = Double.valueOf(hrgjuala);

            String hrgbeli = jFormattedTextFieldhrgBeli.getText();
            String hrgbelia = hrgbeli.replace(",", "");
            double hrgbeliOk = Double.valueOf(hrgbelia);

            String query = "INSERT INTO tabelrealpembelian (noFakturBeli,barcode,jmlBeli,hrgBeli,hrgJual) VALUES ('"+nofakbeli+"','"+barcode+"','"+jumlah+"','"+hrgbeliOk+"','"+hrgjualOk+"')";
            try {
                PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
                ps.executeUpdate();

                txtBarcode.setText("");
                jFormattedTextFieldhrgBeli.setText("");
                txtnmBarang.setText("");
                jTextFieldhrgJual.setText("");
                jTextFieldjmlBeli.setText("");
                
                load_tabelBeli();
                tampil_total();
                        
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
     
    }//GEN-LAST:event_jTextFieldjmlBeliKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariBarangpembelian;
    private javax.swing.JButton btnSimpanpembelian;
    private javax.swing.JComboBox<String> jComboBoxsupplier;
    private javax.swing.JDialog jDialogCariBarang;
    private javax.swing.JFormattedTextField jFormattedTextFieldBayarpembelian;
    private javax.swing.JFormattedTextField jFormattedTextFieldKembaliPembelian;
    private javax.swing.JFormattedTextField jFormattedTextFieldhrgBeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeltotalBeli;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCari;
    private javax.swing.JTextField jTextFieldCariBarang;
    private javax.swing.JTextField jTextFieldhrgJual;
    private javax.swing.JTextField jTextFieldjmlBeli;
    private javax.swing.JTextField jTextFieldkdSupplier;
    private javax.swing.JTextField jTextFieldnoFakturPembelian;
    private javax.swing.JTable tabelPembelian;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtnmBarang;
    // End of variables declaration//GEN-END:variables

    private void tampilNamaFaktur() {
    Date ys=new Date(); // membuat oject ys dari class Date
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy"); //membuat object s dari class SimpleDateFormat dengan format (dd-MM-yyyy)yaitu (tanggal-bulan-tahun).
 
            String TglHrIni = s.format(ys);
            String sql = "Select No as no from tabelpembelian ORDER by No desc";
            try {
                    Statement stm=conn.createStatement();
                    ResultSet rs=stm.executeQuery(sql);

                   if (rs.next())
                    {
                    int no_t = Integer.parseInt(rs.getString("No")) + 1;
                    jTextFieldnoFakturPembelian.setText("FB"+TglHrIni+Integer.toString(no_t));
                    }
                    else{
                    int no_t = 1;
                    jTextFieldnoFakturPembelian.setText("FB"+TglHrIni+Integer.toString(no_t));
                    }
                    rs.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }     
    }
    
    private void tampil_supplier() {
         jComboBoxsupplier.removeAllItems();
         jComboBoxsupplier.addItem("Pilih Supplier");
         
         String query = "select namaSupplier from datasupplier order by namaSupplier asc";
         try {
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
             while (res.next()) {                 
                 jComboBoxsupplier.addItem(res.getString("namaSupplier"));
             }
             res.last();
             int jumlahData = res.getRow();
             res.first();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void load_tabelBeli() {
     String nomorFakturBeli = jTextFieldnoFakturPembelian.getText();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Barcode");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah Beli");
        model.addColumn("Harga Beli");
        model.addColumn("Sub Total");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "SELECT tabelrealpembelian.barcode, databarang.namaBarang, tabelrealpembelian.jmlBeli, tabelrealpembelian.hrgBeli, tabelrealpembelian.jmlBeli * tabelrealpembelian.hrgBeli AS subtotal from tabelrealpembelian,databarang WHERE tabelrealpembelian.barcode = databarang.barcode AND tabelrealpembelian.noFakturBeli='"+nomorFakturBeli+"'";
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                Object[]o=new Object[6];
                o[0]= no++;
                o[1]= res.getString("barcode");
                o[2]= res.getString("namaBarang");
                
                double j = Double.parseDouble(res.getString("jmlBeli"));
                o[3]= String.format("%,.2f", j);
                
                double h = Double.parseDouble(res.getString("hrgBeli"));
                o[4]= String.format("%,.2f", h);
                
                double i = Double.parseDouble(res.getString("Subtotal"));
                o[5]= String.format("%,.2f", i);
                
                model.addRow(o);
            }
            tabelPembelian.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }   
    }

    private void tampil_total() {
        String nomorFaktur = jTextFieldnoFakturPembelian.getText();
        String query="select ifnull(sum(hrgBeli*jmlBeli),0) as Total from tabelrealpembelian where noFakturBeli = '"+nomorFaktur+"'";
        try {
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            
            if(res.next()){
                double h = Double.parseDouble(res.getString("Total"));
                jLabeltotalBeli.setText(String.format("%,.2f", h));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void simpan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
