/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Penjualan;

import Utama.Variabel;
import com.util.FormUtil;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author LENOVO
 */
public class Penjualan extends javax.swing.JInternalFrame {

    Connection conn = (Connection)koneksi.configDB();
    JasperReport JR;
    JasperPrint JP;
    Map<String, Object> param = new HashMap<String, Object >(2);
    JasperDesign JD;
    
    boolean update;
    
    /**
     * Creates new form Penjualan
     */
    public Penjualan() {
        initComponents();
        this.getContentPane().setBackground(new Color(248,250,252));
        tampilNamaFaktur();
        tampil_tabel();
        tampil_total();
        tampil_poin();
        jTableCari.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if((!e.getValueIsAdjusting()&&jTableCari.getSelectedRow()!=-1)){
                    int row = jTableCari.getSelectedRow();
                    String barcode = jTableCari.getValueAt(row, 0).toString();
                    txtBarcode.setText(barcode);
                }
            }
        });
        jTextFieldhrgBeli.setVisible(false);
        jButtonTambahMember.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jDialogTambah = new javax.swing.JDialog();
        jLabelKdPelanggan1 = new javax.swing.JLabel();
        jLabel1NmPelanggan1 = new javax.swing.JLabel();
        jTextFieldNmPelangganTambah = new javax.swing.JTextField();
        jButtonTambahPelanggan1 = new javax.swing.JButton();
        jTextFieldKdPelangganTambah = new javax.swing.JTextField();
        jDialogCariBarang = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCari = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldCariBarang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jpopMenu = new javax.swing.JPopupMenu();
        jItemHapus = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPenjualan = new javax.swing.JTable() {
            public boolean isCellEditable(int row, int column) {
                return false;
            };
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnoFaktur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtkdPelanggan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnmPelanggan = new javax.swing.JTextField();
        jButtonTambahMember = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnmBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldQty = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldjmlPoint = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldhrgJual = new javax.swing.JTextField();
        jTextFieldhrgBeli = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnCariBarang = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldBayar = new javax.swing.JFormattedTextField();
        jFormattedTextFieldKembali = new javax.swing.JFormattedTextField();

        jDialogTambah.setTitle("Tambah Pelanggan");
        jDialogTambah.setSize(new java.awt.Dimension(360, 210));

        jLabelKdPelanggan1.setText("Kode Pelanggan");

        jLabel1NmPelanggan1.setText("Nama Pelanggan ");

        jButtonTambahPelanggan1.setText("Tambah");
        jButtonTambahPelanggan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahPelanggan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogTambahLayout = new javax.swing.GroupLayout(jDialogTambah.getContentPane());
        jDialogTambah.getContentPane().setLayout(jDialogTambahLayout);
        jDialogTambahLayout.setHorizontalGroup(
            jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTambahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogTambahLayout.createSequentialGroup()
                        .addGroup(jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelKdPelanggan1)
                            .addComponent(jLabel1NmPelanggan1))
                        .addGap(41, 41, 41)
                        .addGroup(jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldKdPelangganTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jTextFieldNmPelangganTambah)))
                    .addComponent(jButtonTambahPelanggan1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogTambahLayout.setVerticalGroup(
            jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTambahLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKdPelanggan1)
                    .addComponent(jTextFieldKdPelangganTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1NmPelanggan1)
                    .addComponent(jTextFieldNmPelangganTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButtonTambahPelanggan1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jDialogCariBarang.setSize(new java.awt.Dimension(800, 500));

        jTableCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCariMouseClicked(evt);
            }
        });
        jTableCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableCariKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCari);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 2));

        jTextFieldCariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCariBarangKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCariBarangKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Masukan Nama Barang ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(47, 47, 47)
                .addComponent(jTextFieldCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jDialogCariBarangLayout = new javax.swing.GroupLayout(jDialogCariBarang.getContentPane());
        jDialogCariBarang.getContentPane().setLayout(jDialogCariBarangLayout);
        jDialogCariBarangLayout.setHorizontalGroup(
            jDialogCariBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jDialogCariBarangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogCariBarangLayout.setVerticalGroup(
            jDialogCariBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCariBarangLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        jItemHapus.setText("Hapus");
        jItemHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemHapusActionPerformed(evt);
            }
        });
        jpopMenu.add(jItemHapus);

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Penjualan Barang");

        jScrollPane1.setBackground(new java.awt.Color(250, 250, 250));

        tabelPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jpopMenu, org.jdesktop.beansbinding.ObjectProperty.create(), tabelPenjualan, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        tabelPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPenjualanMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelPenjualanMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPenjualan);
        tabelPenjualan.setFillsViewportHeight(true);
        tabelPenjualan.getTableHeader().setReorderingAllowed(false);
        tabelPenjualan.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(226, 232, 240));

        jLabel2.setText("No Faktur Jual");

        txtnoFaktur.setEnabled(false);

        jLabel6.setText("Kode Pelanggan");

        txtkdPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkdPelangganKeyPressed(evt);
            }
        });

        jLabel7.setText("Nama");

        txtnmPelanggan.setEnabled(false);

        jButtonTambahMember.setBackground(new java.awt.Color(250, 250, 250));
        jButtonTambahMember.setText("+");
        jButtonTambahMember.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTambahMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnoFaktur, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtkdPelanggan))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTambahMember))
                    .addComponent(txtnmPelanggan))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButtonTambahMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnmPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(226, 232, 240));

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotal.setText("0");
        jLabelTotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(226, 232, 240));

        jLabel3.setText("Barcode");

        txtBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyReleased(evt);
            }
        });

        jLabel4.setText("Nama Barang");

        txtnmBarang.setEditable(false);
        txtnmBarang.setEnabled(false);
        txtnmBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmBarangActionPerformed(evt);
            }
        });

        jLabel5.setText("QTY");

        jFormattedTextFieldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldQtyKeyPressed(evt);
            }
        });

        jLabel1.setText("Poin");

        jTextFieldjmlPoint.setEnabled(false);

        jLabel10.setText("Harga Jual");

        jTextFieldhrgJual.setEditable(false);
        jTextFieldhrgJual.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtnmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldhrgJual, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldhrgBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldjmlPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldjmlPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldhrgJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldhrgBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(253, 224, 71));

        btnSimpan.setBackground(new java.awt.Color(241, 245, 249));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnCariBarang.setBackground(new java.awt.Color(241, 245, 249));
        btnCariBarang.setText("Cari Barang");
        btnCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBarangActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("BAYAR");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("KEMBALI");

        jFormattedTextFieldBayar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedTextFieldBayar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFormattedTextFieldBayar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jFormattedTextFieldBayarCaretUpdate(evt);
            }
        });
        jFormattedTextFieldBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldBayarKeyPressed(evt);
            }
        });

        jFormattedTextFieldKembali.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedTextFieldKembali.setEnabled(false);
        jFormattedTextFieldKembali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCariBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextFieldKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldBayar))
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariBarang))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jFormattedTextFieldBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextFieldKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnmBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmBarangActionPerformed

    private void jButtonTambahMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahMemberActionPerformed
        FormUtil.centerWindow(jDialogTambah);
        jDialogTambah.setVisible(true);
    }//GEN-LAST:event_jButtonTambahMemberActionPerformed

    private void txtkdPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkdPelangganKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            String kdpelanggan = txtkdPelanggan.getText();
            if (txtkdPelanggan.getText().length()==0) {
                txtnmPelanggan.setText("");
            } else {
                String sql = "SELECT namaPelanggan from datapelanggan where kdPelanggan = '"+kdpelanggan+"'";
                try {
                    Statement stm=conn.createStatement();
                    ResultSet rs=stm.executeQuery(sql);
                    
                    if (rs.next()){
                        txtnmPelanggan.setText(rs.getString("namaPelanggan"));
                    } else {
                        txtnmPelanggan.setText("");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_txtkdPelangganKeyPressed

    private void jButtonTambahPelanggan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahPelanggan1ActionPerformed
        if (jTextFieldKdPelangganTambah.getText().length()==0) {
            JOptionPane.showMessageDialog(null, "Masukan Kode Pelanggan");
        } else if (jTextFieldNmPelangganTambah.getText().length()==0) {
            JOptionPane.showMessageDialog(null, "Masukan Nama Pelanggan");
        } else {
            String KdPlnggn = jTextFieldKdPelangganTambah.getText();
            String namaPlnggn = jTextFieldNmPelangganTambah.getText();

            String query ="insert into `datapelanggan`(kdPelanggan,namaPelanggan) values ( '"+KdPlnggn+"', '"+namaPlnggn+"')";
            try {
                int pilihan = JOptionPane.showConfirmDialog(null, "Simpan data?","Peringatan",JOptionPane.YES_NO_OPTION);
                if (pilihan==JOptionPane.YES_OPTION) {
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    jDialogTambah.setVisible(false);
                    jDialogTambah.dispose();
                    jTextFieldKdPelangganTambah.setText("");
                    jTextFieldNmPelangganTambah.setText("");
                    txtkdPelanggan.setText(KdPlnggn);
                    txtnmPelanggan.setText(namaPlnggn);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonTambahPelanggan1ActionPerformed

    private void txtBarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String barcode = txtBarcode.getText();
            String nofakjual = txtnoFaktur.getText();
            String namaBarang = txtnmBarang.getText();
            
            String hrgjual = jTextFieldhrgJual.getText();
            String hrgjuala = hrgjual.replace(",", "");
            double hrgjualOk = Double.valueOf(hrgjuala);
            
            String hrgbeli = jTextFieldhrgBeli.getText();
            String hrgbelia = hrgbeli.replace(",", "");
            double hrgbeliOk = Double.valueOf(hrgbelia);
            
            if (!barcode.isEmpty() && namaBarang.isEmpty()) {
                String query = "select namaBarang, hrgJual, hrgBeli from databarang where barcode='"+barcode+"'";
                
                try {
                    Statement stm=conn.createStatement();
                    ResultSet rs=stm.executeQuery(query);
                    if (rs.next()) {

                        String namaBarangGet = rs.getString("namaBarang");                            
                        double hrgJualGet = Double.parseDouble(rs.getString("hrgJual"));
                        double hrgBeliGet = Double.parseDouble(rs.getString("hrgBeli"));

                        String s = "";
                        String qtyFind = "";
                        boolean exists = false;
                        for (int i=0; i<tabelPenjualan.getRowCount(); i++) {    
                            s = tabelPenjualan.getValueAt(i, 1).toString().trim();
                            if(barcode.equals(s)) {
                               exists = true;
                               qtyFind = tabelPenjualan.getValueAt(i, 3).toString();
                               break;
                            }
                        }

                        try {
                            String queryNext;
                            if (!exists) {
                                queryNext = "insert into tabelrealpenjualan (barcode,noFakturJualan,namaBarang,jmlhJual,hrgJual,hrgBeli) values ('"+barcode+"','"+nofakjual+"','"+namaBarangGet+"','"+1+"','"+hrgJualGet+"','"+hrgBeliGet+"')";
                            } else {
                                queryNext = "update tabelrealpenjualan set jmlhJual="+Integer.sum(Integer.parseInt(qtyFind), 1)+" where barcode="+barcode;
                            }
                            PreparedStatement ps = (PreparedStatement) conn.prepareStatement(queryNext);
                            ps.executeUpdate();
                            
                            tampil_tabel();
                            tampil_total();
                            tampil_poin();
                            resetField();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        }
                    } else {
                        resetField();
                    }
                } catch (NumberFormatException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
            
            if (!barcode.isEmpty() && !namaBarang.isEmpty()) {
                String s = "";
                String qtyFind = "";
                boolean exists = false;
                for (int i=0; i<tabelPenjualan.getRowCount(); i++) {    
                    s = tabelPenjualan.getValueAt(i, 1).toString().trim();
                    if(barcode.equals(s)) {
                       exists = true;
                       qtyFind = tabelPenjualan.getValueAt(i, 3).toString();
                       break;
                    }
                }

                try {
                    String queryNext = "";
                    if (!exists) {
                        queryNext = "insert into tabelrealpenjualan (barcode,noFakturJualan,namaBarang,jmlhJual,hrgJual,hrgBeli) values ('"+barcode+"','"+nofakjual+"','"+namaBarang+"','"+1+"','"+hrgjualOk+"','"+hrgbeliOk+"')";
                    } else {
                        queryNext = "update tabelrealpenjualan set jmlhJual="+Integer.sum(Integer.parseInt(qtyFind), 1)+" where barcode="+barcode;
                    }
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(queryNext);
                    ps.executeUpdate();
                    
                    tampil_tabel();
                    tampil_total();
                    tampil_poin();
                    resetField();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_txtBarcodeKeyPressed

    private void jFormattedTextFieldQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldQtyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String nofakjual = txtnoFaktur.getText();
            String barcode = txtBarcode.getText();
            String jml = jFormattedTextFieldQty.getText();

            String namaBarang = txtnmBarang.getText();

            String hrgjual = jTextFieldhrgJual.getText();
            String hrgjuala = hrgjual.replace(",", "");
            double hrgjualOk = Double.valueOf(hrgjuala);
            
            String hrgbeli = jTextFieldhrgBeli.getText();
            String hrgbelia = hrgbeli.replace(",", "");
            double hrgbeliOk = Double.valueOf(hrgbelia);
            
            if (!namaBarang.isEmpty()) {
                String s = "";
                String qtyFind = "";
                boolean exists = false;
                for (int i=0; i<tabelPenjualan.getRowCount(); i++) {    
                    s = tabelPenjualan.getValueAt(i, 1).toString().trim();
                    if(barcode.equals(s)) {
                       exists = true;
                       qtyFind = tabelPenjualan.getValueAt(i, 3).toString();
                       break;
                    }
                }

                try {
                    String queryNext = "";
                    if (!exists) {
                        queryNext = "insert into tabelrealpenjualan (barcode,noFakturJualan,namaBarang,jmlhJual,hrgJual,hrgBeli) values ('"+barcode+"','"+nofakjual+"','"+namaBarang+"','"+(jml.isEmpty() ? 1 : jml)+"','"+hrgjualOk+"','"+hrgbeliOk+"')";
                    } 
                    if (exists) {
                        queryNext = "update tabelrealpenjualan set jmlhJual="+Integer.sum(Integer.parseInt(qtyFind), Integer.parseInt(jml))+" where barcode="+barcode;
                    }
                    if (update) {
                        queryNext = "update tabelrealpenjualan set jmlhJual="+jml+" where barcode="+barcode;
                    }
                    
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement(queryNext);
                    ps.executeUpdate();
                    
                    tampil_tabel();
                    tampil_total();
                    tampil_poin();
                    resetField();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                update = false;
            }
        }
    }//GEN-LAST:event_jFormattedTextFieldQtyKeyPressed

    private void jFormattedTextFieldBayarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jFormattedTextFieldBayarCaretUpdate
        if (jFormattedTextFieldBayar.getText().length() != 0) {
            String bayar = jFormattedTextFieldBayar.getText();
            String bayarOke = bayar.replace(",", "");
            double pembayaran = Double.valueOf(bayarOke);
            String total = jLabelTotal.getText();
            String totalbayar = total.replace(",", "");
            double totalFormat = Double.valueOf(totalbayar);

            double kembali = pembayaran - totalFormat;
            jFormattedTextFieldKembali.setText(String.format("%,.2f", kembali));   
        }
    }//GEN-LAST:event_jFormattedTextFieldBayarCaretUpdate

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBarangActionPerformed
        FormUtil.centerWindow(jDialogCariBarang);
        jDialogCariBarang.setVisible(true);
        load_table();
    }//GEN-LAST:event_btnCariBarangActionPerformed

    private void jTextFieldCariBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCariBarangKeyReleased
        load_table();        
    }//GEN-LAST:event_jTextFieldCariBarangKeyReleased

    private void jFormattedTextFieldBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldBayarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            simpan();
        }
    }//GEN-LAST:event_jFormattedTextFieldBayarKeyPressed

    private void jTableCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCariMouseClicked
        int baris = jTableCari.rowAtPoint(evt.getPoint());
        String barcode =jTableCari.getValueAt(baris, 0).toString();
        txtBarcode.setText(barcode);
        
        String query = "select namaBarang,hrgJual,hrgBeli from databarang where barcode ='"+barcode+"'";
        
        try {
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery(query);

                if (rs.next()) {
                   txtnmBarang.setText(rs.getString("namaBarang"));
                   double hrgJual = Double.parseDouble(rs.getString("hrgJual"));
                   jTextFieldhrgJual.setText(String.format("%,.2f", hrgJual));

                   double hrgBeli = Double.parseDouble(rs.getString("hrgBeli"));
                   jTextFieldhrgBeli.setText(String.format("%,.2f", hrgBeli));


                   jDialogCariBarang.setVisible(false);
                   jDialogCariBarang.dispose();

                   jFormattedTextFieldQty.requestFocus();
                } else {
                   resetField();
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTableCariMouseClicked

    private void jTextFieldCariBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCariBarangKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTableCari.getSelectionModel().addSelectionInterval(0, 0);
            jTableCari.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldCariBarangKeyPressed

    private void jTableCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String barcode = txtBarcode.getText();
            String query = "select namaBarang,hrgJual,hrgBeli from databarang where barcode ='"+barcode+"'";
            
            try {
                Statement stm=conn.createStatement();
                ResultSet rs=stm.executeQuery(query);
                    
                if (rs.next()) {
                    txtnmBarang.setText(rs.getString("namaBarang"));
                    double hrgJual = Double.parseDouble(rs.getString("hrgJual"));
                    jTextFieldhrgJual.setText(String.format("%,.2f", hrgJual));

                    double hrgBeli = Double.parseDouble(rs.getString("hrgBeli"));
                    jTextFieldhrgBeli.setText(String.format("%,.2f", hrgBeli));

                    jDialogCariBarang.setVisible(false);
                    jDialogCariBarang.dispose();

                    jFormattedTextFieldQty.requestFocus();
                } else {
                    resetField();
                }
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jTableCariKeyPressed

    private void txtBarcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_ENTER) {
            String barcode = txtBarcode.getText();
            String query = "select namaBarang,hrgJual,hrgBeli from databarang where barcode='"+barcode+"'";

            try {
                Statement stm=conn.createStatement();
                ResultSet rs=stm.executeQuery(query);

                if (rs.next()) {
                    txtnmBarang.setText(rs.getString("namaBarang"));

                    double hrgJual = Double.parseDouble(rs.getString("hrgJual"));
                    jTextFieldhrgJual.setText(String.format("%,.2f", hrgJual));

                    double hrgBeli = Double.parseDouble(rs.getString("hrgBeli"));
                    jTextFieldhrgBeli.setText(String.format("%,.2f", hrgBeli));
                 } else {
                    resetField();
                 }
            } catch (Exception e) {
                System.err.println(e.getMessage());
            }   
        }
    }//GEN-LAST:event_txtBarcodeKeyReleased

    private void tabelPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPenjualanMouseClicked
        if (evt.getClickCount() == 2 && tabelPenjualan.getSelectedRow() != -1) {
            int baris = tabelPenjualan.rowAtPoint(evt.getPoint());

            txtBarcode.setText(tabelPenjualan.getValueAt(baris, 1).toString());
            txtnmBarang.setText(tabelPenjualan.getValueAt(baris, 2).toString());
            jFormattedTextFieldQty.setText(tabelPenjualan.getValueAt(baris, 3).toString());
            jTextFieldhrgJual.setText(tabelPenjualan.getValueAt(baris, 4).toString());
            jTextFieldhrgBeli.setText(tabelPenjualan.getValueAt(baris, 5).toString());
            update = true;   
        }
    }//GEN-LAST:event_tabelPenjualanMouseClicked

    private void tabelPenjualanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPenjualanMouseReleased
        if (evt.isPopupTrigger())
        {
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );

            if (!source.isRowSelected(row)) {
                source.changeSelection(row, column, false, false);
            }
            
            jpopMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tabelPenjualanMouseReleased

    private void jItemHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemHapusActionPerformed
        hapus(tabelPenjualan.getValueAt(tabelPenjualan.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_jItemHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariBarang;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton jButtonTambahMember;
    private javax.swing.JButton jButtonTambahPelanggan1;
    private javax.swing.JDialog jDialogCariBarang;
    private javax.swing.JDialog jDialogTambah;
    private javax.swing.JFormattedTextField jFormattedTextFieldBayar;
    private javax.swing.JFormattedTextField jFormattedTextFieldKembali;
    private javax.swing.JFormattedTextField jFormattedTextFieldQty;
    private javax.swing.JMenuItem jItemHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel1NmPelanggan1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelKdPelanggan1;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCari;
    private javax.swing.JTextField jTextFieldCariBarang;
    private javax.swing.JTextField jTextFieldKdPelangganTambah;
    private javax.swing.JTextField jTextFieldNmPelangganTambah;
    private javax.swing.JTextField jTextFieldhrgBeli;
    private javax.swing.JTextField jTextFieldhrgJual;
    private javax.swing.JTextField jTextFieldjmlPoint;
    private javax.swing.JPopupMenu jpopMenu;
    private javax.swing.JTable tabelPenjualan;
    public javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtkdPelanggan;
    private javax.swing.JTextField txtnmBarang;
    private javax.swing.JTextField txtnmPelanggan;
    private javax.swing.JTextField txtnoFaktur;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void tampilNamaFaktur() {
        Date ys = new Date(); // membuat oject ys dari class Date
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy"); //membuat object s dari class SimpleDateFormat dengan format (dd-MM-yyyy)yaitu (tanggal-bulan-tahun).
 
        String TglHrIni = s.format(ys);
        String sql = "Select No as no from tabel_penjualan ORDER by No desc";
        
        try {
            Statement stm=conn.createStatement();
            ResultSet rs=stm.executeQuery(sql);

            if (rs.next()) {
                int no_t = Integer.parseInt(rs.getString("No")) + 1;
                txtnoFaktur.setText("FJ"+TglHrIni+"N"+Integer.toString(no_t));
            } else {
                int no_t = 1;
                txtnoFaktur.setText("FJ"+TglHrIni+"N"+Integer.toString(no_t));
            }
            
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } 
    }

    private void tampil_tabel() {
        String nomorFaktur = txtnoFaktur.getText();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Barcode");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah Jual");
        model.addColumn("Harga Jual");
        model.addColumn("Harga Beli");
        model.addColumn("Sub Total");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select no,barcode,namaBarang,jmlhJual,hrgJual,hrgBeli, jmlhJual*hrgJual as subtotal from tabelrealpenjualan where noFakturJualan ='"+nomorFaktur+"'";
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);
            while(res.next()) {
                Object[]o = new Object[7];
                o[0] = no++;
                o[1] = res.getString("barcode");
                o[2] = res.getString("namaBarang");
                
                o[3] = res.getString("jmlhJual");
                
                double j = Double.parseDouble(res.getString("hrgJual"));
                o[4] = String.format("%,.2f", j);
                
                double b = Double.parseDouble(res.getString("hrgBeli"));
                o[5] = String.format("%,.2f", b);
                
                double i = Double.parseDouble(res.getString("subtotal"));
                o[6] = String.format("%,.2f", i);
                
                model.addRow(o);
            }
            tabelPenjualan.setModel(model);
            tabelPenjualan.removeColumn(tabelPenjualan.getColumnModel().getColumn(5));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void tampil_total() {
        String nomorFaktur = txtnoFaktur.getText();
        String query="select ifnull(sum(hrgJual*jmlhJual),0) as Total from tabelrealpenjualan where noFakturJualan = '"+nomorFaktur+"'";
        
        try {
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            
            if(res.next()){
                double h = Double.parseDouble(res.getString("Total"));
                jLabelTotal.setText(String.format("%,.2f", h));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void simpan() {
        String nofakjual = txtnoFaktur.getText();
        String kdPelanggan = txtkdPelanggan.getText();
        
        String jml = jLabelTotal.getText();
        String jmla = jml.replace(",", "");
        double total = Double.valueOf(jmla);
        
        String bayar = jFormattedTextFieldBayar.getText();
        String bayara = bayar.replace(",", "");
        double bayarOk = Double.valueOf(bayara);
        
        String kdUser = Variabel.getkdUser();
        
        String poin = jTextFieldjmlPoint.getText();
        String poina = poin.replace(",", "");
        double poinOk = Double.valueOf(poina);
        
        String query = "insert into tabel_penjualan (No_Faktur_Jual,Tgl_Jual,Kd_Pelanggan,Total,Bayar,Kd_User,poin) values ('"+nofakjual+"',CurDate(),'"+kdPelanggan+"','"+total+"','"+bayarOk+"','"+kdUser+"','"+poinOk+"')";
        
        try {
            PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
            ps.executeUpdate();

            cetak(nofakjual);

            tampilNamaFaktur();
            tampil_tabel();
            tampil_total();
            tampil_poin();
            
            txtkdPelanggan.setText("");
            txtnmPelanggan.setText("");
            jTextFieldjmlPoint.setText("");
            jFormattedTextFieldBayar.setText("");
            jFormattedTextFieldKembali.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void tampil_poin() {
        if (txtkdPelanggan.getText().length() == 0) {
            jTextFieldjmlPoint.setText("0");
        } else {
            String nomorFaktur = txtnoFaktur.getText();
            String query="select ifnull(sum(hrgJual*jmlhJual),0) as Total , kelipatan from tabelrealpenjualan,point where noFakturJualan = '"+nomorFaktur+"'";            
            
            try {
                Statement stm=conn.createStatement();
                ResultSet res=stm.executeQuery(query);

                if(res.next()){
                    double total = Double.parseDouble(res.getString("Total"));
                    double kelipatan = Double.parseDouble(res.getString("kelipatan"));
                    double poin = total/kelipatan;
                    jTextFieldjmlPoint.setText(String.format("%,.2f", poin));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }   
      }
    }
    
    private void load_table(){
        String nama = jTextFieldCariBarang.getText();
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        // model.addColumn("No");
        model.addColumn("Barcode");
        model.addColumn("Nama Barang");
        model.addColumn("Satuan");
        model.addColumn("Kategori");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        
        //menampilkan data database kedalam tabel
        try {
            String sql = "select * from databarang where namaBarang like '%"+nama+"%'";
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                Object[]o=new Object[6];
                o[0]= res.getString("barcode");
                o[1]= res.getString("namaBarang");
                o[2]= res.getString("kdSatuan");
                o[3]= res.getString("kdKategori");
                double k = Double.parseDouble(res.getString("hrgJual"));
                o[4]= String.format("%,.2f", k);
                double l = Double.parseDouble(res.getString("stok"));
                o[5]= String.format("%,.2f", l);
//                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),});
                model.addRow(o);
            }
            jTableCari.setModel(model);
        } catch (NumberFormatException | SQLException e) {
            System.out.println(e.getMessage());
        }
}

    private void cetak(String nofakjual) {
        try {
            File jasper = new File("src/LaporanPenjualan/notapenjualan.jrxml");
            JasperDesign JD = JRXmlLoader.load(jasper);
            
            param.put("noFakturJual", nofakjual);
            JR = JasperCompileManager.compileReport(JD);
            JP = JasperFillManager.fillReport(JR, param,conn);
//            Muncul preview Report
//            JasperViewer.viewReport(JP, false);
//            Langsung print
           JasperPrintManager.printReport(JP, false);
        } catch (JRException e) {
            System.err.println(e.getMessage());
        }
        
    }
    
    public void resetField() {
        txtBarcode.setText("");
        txtnmBarang.setText("");
        jTextFieldhrgJual.setText("");
        jTextFieldhrgBeli.setText("");
        jFormattedTextFieldQty.setText("");
        txtBarcode.requestFocus();
    }

    private void hapus(String barcode) {
        String queryDelete = "delete from tabelrealpenjualan where barcode='"+barcode+"'";

        try {
            PreparedStatement ps = (PreparedStatement) conn.prepareStatement(queryDelete);
            ps.executeUpdate();
            
            tampil_tabel();
            tampil_total();
            tampil_poin();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error saat menghapus data");
        }   
    }
}
